-- =====================================================================
--  Klipse 통합 셋업 SQL  (Supabase SQL Editor 에 그대로 붙여넣어 1회 실행)
--  순서: 공용함수 → 메인비주얼 → 렌탈(브랜드/카테고리/상품/주문/입점문의)
--        → 기존 테이블 보정(inquiry_questions / construction_inquiries) → 인덱스
--  ⚠️ 레거시 main_visuals 테이블은 폐기되고 main_visual_banners 로 대체됩니다.
-- =====================================================================

-- 0) updated_at 자동 갱신 공용 함수 -----------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- A. 메인 비주얼 (시공/렌탈/DJ, Type A 기본 / Type B 쿠폰형)
-- =====================================================================
DROP TABLE IF EXISTS public.main_visuals CASCADE;          -- 레거시 폐기
DROP TABLE IF EXISTS public.main_visual_banners CASCADE;

CREATE TABLE public.main_visual_banners (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section       TEXT NOT NULL CHECK (section IN ('construction', 'rental', 'dj')),
  type          TEXT NOT NULL DEFAULT 'type_a' CHECK (type IN ('type_a', 'type_b')),
  is_ad         BOOLEAN NOT NULL DEFAULT false,
  image_url     TEXT,
  image_mobile_url TEXT,
  badge         TEXT,
  title         TEXT NOT NULL,
  subtitle      TEXT,
  cta_text      TEXT,
  link_url      TEXT,
  author_name   TEXT,
  author_avatar TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);
CREATE INDEX idx_mvb_section_active ON public.main_visual_banners (section, is_active, display_order);
CREATE TRIGGER trg_main_visual_banners_updated BEFORE UPDATE ON public.main_visual_banners
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.main_visual_banners ENABLE ROW LEVEL SECURITY;
CREATE POLICY "mvb public read" ON public.main_visual_banners FOR SELECT USING (true);
CREATE POLICY "mvb admin all"   ON public.main_visual_banners FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT ON public.main_visual_banners TO anon;
GRANT ALL    ON public.main_visual_banners TO authenticated;

-- 샘플(선택)
INSERT INTO public.main_visual_banners (section, type, image_url, badge, title, subtitle, cta_text, link_url, display_order, created_by, updated_by) VALUES
  ('construction', 'type_a', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&q=80&auto=format&fit=crop', NULL, E'공간을 바꾸는\nKlipse 시공', '검증된 시공팀과 함께하는 프리미엄 인테리어', NULL, NULL, 0, 'system', 'system'),
  ('construction', 'type_b', 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&q=80&auto=format&fit=crop', '상담 이벤트', '무료 방문 견적', '지금 신청하면 시공 상담 무료', '시공 문의하기', '/construction-inquiry', 1, 'system', 'system'),
  ('rental', 'type_a', 'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=900&q=80&auto=format&fit=crop', NULL, E'거실부터\n다이닝까지, 피아바', '하나의 취향으로 완성하는 라이프스타일 컬렉션', NULL, NULL, 0, 'system', 'system'),
  ('rental', 'type_b', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=900&q=80&auto=format&fit=crop', '빈백 특가 세일', '요기보 최대 44%', '최대 27만원 할인', '브랜드쿠폰 최대 20%', NULL, 1, 'system', 'system');

-- =====================================================================
-- B. 렌탈 — 브랜드 / 카테고리 / 상품
--    (기존 부분 생성분이 있어도 깨끗이 재생성되도록 DROP 후 CREATE)
-- =====================================================================
DROP TABLE IF EXISTS public.rental_purchase_inquiries CASCADE;
DROP TABLE IF EXISTS public.rental_orders             CASCADE;
DROP TABLE IF EXISTS public.rental_products           CASCADE;
DROP TABLE IF EXISTS public.rental_categories         CASCADE;
DROP TABLE IF EXISTS public.rental_brands             CASCADE;

CREATE TABLE IF NOT EXISTS public.rental_brands (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  logo_url      TEXT,
  description   TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

CREATE TABLE IF NOT EXISTS public.rental_categories (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id      BIGINT REFERENCES public.rental_brands(id) ON DELETE CASCADE,
  parent_id     BIGINT REFERENCES public.rental_categories(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  description   TEXT,
  image_url     TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

CREATE TABLE IF NOT EXISTS public.rental_products (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id      BIGINT REFERENCES public.rental_brands(id) ON DELETE SET NULL,
  category_id   BIGINT REFERENCES public.rental_categories(id) ON DELETE SET NULL,
  name          TEXT NOT NULL,
  description   TEXT,
  thumbnail_url TEXT,
  images        JSONB NOT NULL DEFAULT '[]'::jsonb,
  daily_price   NUMERIC NOT NULL DEFAULT 0,
  deposit       NUMERIC NOT NULL DEFAULT 0,
  delivery_fee  NUMERIC NOT NULL DEFAULT 0,
  stock         INTEGER NOT NULL DEFAULT 0,
  min_days      INTEGER NOT NULL DEFAULT 1,
  max_days      INTEGER,
  options       JSONB NOT NULL DEFAULT '[]'::jsonb,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  is_exclusive  BOOLEAN NOT NULL DEFAULT false,
  is_event      BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

CREATE INDEX IF NOT EXISTS idx_rental_categories_brand ON public.rental_categories (brand_id, display_order);
CREATE INDEX IF NOT EXISTS idx_rental_products_brand_cat ON public.rental_products (brand_id, category_id, display_order);

DROP TRIGGER IF EXISTS trg_rental_brands_updated ON public.rental_brands;
CREATE TRIGGER trg_rental_brands_updated BEFORE UPDATE ON public.rental_brands
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
DROP TRIGGER IF EXISTS trg_rental_categories_updated ON public.rental_categories;
CREATE TRIGGER trg_rental_categories_updated BEFORE UPDATE ON public.rental_categories
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
DROP TRIGGER IF EXISTS trg_rental_products_updated ON public.rental_products;
CREATE TRIGGER trg_rental_products_updated BEFORE UPDATE ON public.rental_products
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.rental_brands     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rental_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rental_products   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "rb read"  ON public.rental_brands;
DROP POLICY IF EXISTS "rb admin" ON public.rental_brands;
DROP POLICY IF EXISTS "rc read"  ON public.rental_categories;
DROP POLICY IF EXISTS "rc admin" ON public.rental_categories;
DROP POLICY IF EXISTS "rp read"  ON public.rental_products;
DROP POLICY IF EXISTS "rp admin" ON public.rental_products;
CREATE POLICY "rb read"  ON public.rental_brands     FOR SELECT USING (true);
CREATE POLICY "rb admin" ON public.rental_brands     FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "rc read"  ON public.rental_categories FOR SELECT USING (true);
CREATE POLICY "rc admin" ON public.rental_categories FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "rp read"  ON public.rental_products   FOR SELECT USING (true);
CREATE POLICY "rp admin" ON public.rental_products   FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT ON public.rental_brands, public.rental_categories, public.rental_products TO anon;
GRANT ALL    ON public.rental_brands, public.rental_categories, public.rental_products TO authenticated;

-- =====================================================================
-- C. 렌탈 — 주문(결제) / 입점 문의(중고매입)
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.rental_orders (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id     BIGINT REFERENCES public.rental_products(id) ON DELETE SET NULL,
  product_name   TEXT,
  brand_name     TEXT,
  option_name    TEXT,
  customer_name  TEXT,
  customer_phone TEXT,
  customer_email TEXT,
  rental_start   TIMESTAMPTZ,
  rental_days    INTEGER NOT NULL DEFAULT 1,
  rental_end     TIMESTAMPTZ,
  quantity       INTEGER NOT NULL DEFAULT 1,
  daily_price    NUMERIC NOT NULL DEFAULT 0,
  deposit        NUMERIC NOT NULL DEFAULT 0,
  delivery_fee   NUMERIC NOT NULL DEFAULT 0,
  total_amount   NUMERIC NOT NULL DEFAULT 0,
  payment_status TEXT NOT NULL DEFAULT 'paid'  CHECK (payment_status IN ('pending','paid','cancelled','refunded')),
  payment_method TEXT,
  payment_id     TEXT,
  order_status   TEXT NOT NULL DEFAULT 'reserved' CHECK (order_status IN ('reserved','renting','returned','cancelled')),
  memo           TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by     TEXT
);

CREATE TABLE IF NOT EXISTS public.rental_purchase_inquiries (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      BIGINT REFERENCES public.rental_products(id) ON DELETE SET NULL,
  product_name    TEXT NOT NULL,
  brand_name      TEXT,
  condition_grade TEXT NOT NULL DEFAULT 'A' CHECK (condition_grade IN ('C','B','A','A+','A++')),
  desired_price   NUMERIC NOT NULL DEFAULT 0,
  images          JSONB NOT NULL DEFAULT '[]'::jsonb,
  description     TEXT,
  applicant_name  TEXT,
  applicant_phone TEXT,
  applicant_email TEXT,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','hold','rejected')),
  admin_memo      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by      TEXT
);

CREATE INDEX IF NOT EXISTS idx_rental_orders_product ON public.rental_orders (product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rental_orders_status  ON public.rental_orders (order_status, payment_status);
CREATE INDEX IF NOT EXISTS idx_rental_purchase_status ON public.rental_purchase_inquiries (status, created_at DESC);

DROP TRIGGER IF EXISTS trg_rental_orders_updated ON public.rental_orders;
CREATE TRIGGER trg_rental_orders_updated BEFORE UPDATE ON public.rental_orders
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
DROP TRIGGER IF EXISTS trg_rental_purchase_updated ON public.rental_purchase_inquiries;
CREATE TRIGGER trg_rental_purchase_updated BEFORE UPDATE ON public.rental_purchase_inquiries
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.rental_orders             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rental_purchase_inquiries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ro insert"  ON public.rental_orders;
DROP POLICY IF EXISTS "ro admin"   ON public.rental_orders;
DROP POLICY IF EXISTS "rpi insert" ON public.rental_purchase_inquiries;
DROP POLICY IF EXISTS "rpi admin"  ON public.rental_purchase_inquiries;
CREATE POLICY "ro insert"  ON public.rental_orders FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "ro admin"   ON public.rental_orders FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "rpi insert" ON public.rental_purchase_inquiries FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "rpi admin"  ON public.rental_purchase_inquiries FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT INSERT ON public.rental_orders, public.rental_purchase_inquiries TO anon;
GRANT ALL    ON public.rental_orders, public.rental_purchase_inquiries TO authenticated;

-- =====================================================================
-- D. 기존 테이블 보정 (앱 동작에 필요)
-- =====================================================================
-- 챗봇 룰베이스(inquiry_questions) 컬럼 보강
ALTER TABLE public.inquiry_questions
  ADD COLUMN IF NOT EXISTS is_active      BOOLEAN     NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS use_categories BOOLEAN     NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at     TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  ADD COLUMN IF NOT EXISTS updated_at     TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  ADD COLUMN IF NOT EXISTS created_by     TEXT,
  ADD COLUMN IF NOT EXISTS updated_by     TEXT;
UPDATE public.inquiry_questions SET display_order = 0 WHERE display_order IS NULL;
ALTER TABLE public.inquiry_questions ALTER COLUMN display_order SET DEFAULT 0;

DROP TRIGGER IF EXISTS trg_inquiry_questions_updated ON public.inquiry_questions;
CREATE TRIGGER trg_inquiry_questions_updated BEFORE UPDATE ON public.inquiry_questions
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.inquiry_questions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "iq read"  ON public.inquiry_questions;
DROP POLICY IF EXISTS "iq admin" ON public.inquiry_questions;
CREATE POLICY "iq read"  ON public.inquiry_questions FOR SELECT USING (true);
CREATE POLICY "iq admin" ON public.inquiry_questions FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT ON public.inquiry_questions TO anon;
GRANT ALL    ON public.inquiry_questions TO authenticated;

-- 시공 문의 동의 컬럼 보강
ALTER TABLE public.construction_inquiries
  ADD COLUMN IF NOT EXISTS privacy_agree   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS marketing_agree BOOLEAN NOT NULL DEFAULT false;

-- =====================================================================
-- E. 성능 인덱스
-- =====================================================================
CREATE INDEX IF NOT EXISTS idx_reviews_category   ON public.construction_reviews (category_id, display_order);
CREATE INDEX IF NOT EXISTS idx_reviews_active     ON public.construction_reviews (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_portfolio_category ON public.construction_portfolio (category_id, display_order);
CREATE INDEX IF NOT EXISTS idx_portfolio_active   ON public.construction_portfolio (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_categories_active  ON public.construction_categories (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_iq_order           ON public.inquiry_questions (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_cinq_created       ON public.construction_inquiries (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cinq_status        ON public.construction_inquiries (status);

-- =====================================================================
-- G. 환경설정: 회사정보 / 부서 / 부서별권한 / 관리자 프로필
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.company_info (
  id INTEGER PRIMARY KEY DEFAULT 1,
  site_name TEXT, ceo_name TEXT, biz_name TEXT, biz_number TEXT, mail_order_number TEXT,
  phone TEXT, fax TEXT, address TEXT, privacy_officer TEXT, privacy_email TEXT,
  ad_email TEXT, cs_email TEXT, cs_phone TEXT, tagline TEXT,
  sns JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), updated_by TEXT,
  CONSTRAINT company_info_singleton CHECK (id = 1)
);
DROP TRIGGER IF EXISTS trg_company_info_updated ON public.company_info;
CREATE TRIGGER trg_company_info_updated BEFORE UPDATE ON public.company_info FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
ALTER TABLE public.company_info ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ci read"  ON public.company_info;
DROP POLICY IF EXISTS "ci admin" ON public.company_info;
CREATE POLICY "ci read"  ON public.company_info FOR SELECT USING (true);
CREATE POLICY "ci admin" ON public.company_info FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT ON public.company_info TO anon;
GRANT ALL    ON public.company_info TO authenticated;
INSERT INTO public.company_info (id, site_name, ceo_name, biz_name, biz_number, phone, address, cs_email, tagline)
VALUES (1, '클립스', '홍길동', '(주)클립스', '123-45-67890', '1600-0000', '서울특별시 서초구 서초대로 74길', 'help@klipse.com', '공간에 딱 맞는 사운드와 시공을 제안하는 클립스')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  menu_keys JSONB NOT NULL DEFAULT '[]'::jsonb,
  permissions JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW())
);
DROP TRIGGER IF EXISTS trg_departments_updated ON public.departments;
CREATE TRIGGER trg_departments_updated BEFORE UPDATE ON public.departments FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.admins
  ADD COLUMN IF NOT EXISTS auth_user_id  UUID,
  ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES public.departments(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS desired_email TEXT;

ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins      ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "dept admin"   ON public.departments;
DROP POLICY IF EXISTS "admins admin" ON public.admins;
CREATE POLICY "dept admin"   ON public.departments FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admins admin" ON public.admins      FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT ALL ON public.departments TO authenticated;
GRANT ALL ON public.admins TO authenticated;

-- =====================================================================
-- H. DJ 입점(아티스트 회원)
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.dj_artists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, stage_name TEXT, phone TEXT, email TEXT,
  id_card_url TEXT, bankbook_url TEXT, resume_url TEXT,
  portfolio_type TEXT NOT NULL DEFAULT 'img' CHECK (portfolio_type IN ('pdf','img')),
  portfolio_files JSONB NOT NULL DEFAULT '[]'::jsonb,
  soundcloud_url TEXT, mp3_url TEXT, youtube_url TEXT,
  social_links JSONB NOT NULL DEFAULT '[]'::jsonb,
  regions JSONB NOT NULL DEFAULT '[]'::jsonb,
  guarantee_seoul NUMERIC, guarantee_gyeonggi NUMERIC, guarantee_daejeon NUMERIC,
  intro TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','hold','rejected')),
  admin_memo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_dj_artists_status ON public.dj_artists (status, created_at DESC);
DROP TRIGGER IF EXISTS trg_dj_artists_updated ON public.dj_artists;
CREATE TRIGGER trg_dj_artists_updated BEFORE UPDATE ON public.dj_artists FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
ALTER TABLE public.dj_artists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "dj insert" ON public.dj_artists;
DROP POLICY IF EXISTS "dj admin"  ON public.dj_artists;
CREATE POLICY "dj insert" ON public.dj_artists FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "dj admin"  ON public.dj_artists FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT INSERT ON public.dj_artists TO anon;
GRANT ALL    ON public.dj_artists TO authenticated;

-- =====================================================================
-- I. 약관 관리 (서비스 이용약관 / 개인정보 처리방침)
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.terms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('service','privacy')),
  title TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  version TEXT,
  effective_date DATE,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_terms_type ON public.terms (type, display_order);
DROP TRIGGER IF EXISTS trg_terms_updated ON public.terms;
CREATE TRIGGER trg_terms_updated BEFORE UPDATE ON public.terms FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
ALTER TABLE public.terms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "terms read"  ON public.terms;
DROP POLICY IF EXISTS "terms admin" ON public.terms;
CREATE POLICY "terms read"  ON public.terms FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "terms admin" ON public.terms FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT ON public.terms TO anon;
GRANT ALL    ON public.terms TO authenticated;

-- =====================================================================
-- J. 시공 업무 관리(업체/업무) + 견적서(시공/렌탈/DJ)
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.construction_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, manager TEXT, phone TEXT, email TEXT, region TEXT, memo TEXT,
  display_order INTEGER NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), created_by TEXT, updated_by TEXT
);
CREATE TABLE IF NOT EXISTS public.construction_works (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_id BIGINT, title TEXT NOT NULL, customer_name TEXT, customer_phone TEXT,
  company_id BIGINT REFERENCES public.construction_companies(id) ON DELETE SET NULL, company_name TEXT, assignee TEXT,
  scheduled_start DATE, scheduled_end DATE, amount NUMERIC,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','assigned','in_progress','done','hold')),
  memo TEXT, display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_con_works_sched ON public.construction_works (scheduled_start);
CREATE TABLE IF NOT EXISTS public.estimates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('construction','rental','dj')),
  title TEXT NOT NULL, customer_name TEXT, customer_phone TEXT, customer_email TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  subtotal NUMERIC NOT NULL DEFAULT 0, discount NUMERIC NOT NULL DEFAULT 0, tax NUMERIC NOT NULL DEFAULT 0, total NUMERIC NOT NULL DEFAULT 0,
  valid_until DATE, status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','accepted','rejected')),
  memo TEXT, display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_estimates_type ON public.estimates (type, created_at DESC);
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['construction_companies','construction_works','estimates'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_updated ON public.%I;', t, t);
    EXECUTE format('CREATE TRIGGER trg_%s_updated BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();', t, t);
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('DROP POLICY IF EXISTS "%s admin" ON public.%I;', t, t);
    EXECUTE format('CREATE POLICY "%s admin" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true);', t, t);
    EXECUTE format('GRANT ALL ON public.%I TO authenticated;', t);
  END LOOP;
END $$;

-- =====================================================================
-- K. DJ 행사(섭외) 문의
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.dj_event_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  customer_name TEXT, customer_phone TEXT, customer_email TEXT,
  event_date DATE, event_time TEXT, region TEXT, venue TEXT, budget NUMERIC,
  artist_id BIGINT REFERENCES public.dj_artists(id) ON DELETE SET NULL, artist_name TEXT, guests INTEGER,
  message TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','consulting','confirmed','done','cancelled')),
  admin_memo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_dj_events_date ON public.dj_event_inquiries (event_date);
CREATE INDEX IF NOT EXISTS idx_dj_events_status ON public.dj_event_inquiries (status, created_at DESC);
DROP TRIGGER IF EXISTS trg_dj_events_updated ON public.dj_event_inquiries;
CREATE TRIGGER trg_dj_events_updated BEFORE UPDATE ON public.dj_event_inquiries FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
ALTER TABLE public.dj_event_inquiries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "dj ev insert" ON public.dj_event_inquiries;
DROP POLICY IF EXISTS "dj ev admin"  ON public.dj_event_inquiries;
CREATE POLICY "dj ev insert" ON public.dj_event_inquiries FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "dj ev admin"  ON public.dj_event_inquiries FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT INSERT ON public.dj_event_inquiries TO anon;
GRANT ALL    ON public.dj_event_inquiries TO authenticated;

-- =====================================================================
-- L. 계약서(문서) 관리
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template TEXT NOT NULL CHECK (template IN ('freelancer','construction_order','event_order','rental_handover','rental')),
  title TEXT NOT NULL, customer_name TEXT,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','completed')),
  inquiry_id BIGINT, owner_user_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_contracts_template ON public.contracts (template, created_at DESC);
DROP TRIGGER IF EXISTS trg_contracts_updated ON public.contracts;
CREATE TRIGGER trg_contracts_updated BEFORE UPDATE ON public.contracts FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "contracts admin" ON public.contracts;
DROP POLICY IF EXISTS "contracts owner read" ON public.contracts;
CREATE POLICY "contracts admin" ON public.contracts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "contracts owner read" ON public.contracts FOR SELECT TO authenticated USING (owner_user_id = auth.uid());
GRANT ALL ON public.contracts TO authenticated;

-- =====================================================================
-- F. (선택) 미사용 레거시 테이블 정리 — 필요 시 주석 해제 (백업 권장)
-- =====================================================================
-- DROP TABLE IF EXISTS public.inquiry_options CASCADE;
-- DROP TABLE IF EXISTS public.inquiry_files   CASCADE;
-- DROP TABLE IF EXISTS public.inquiry_answers CASCADE;
-- DROP TABLE IF EXISTS public.inquiries       CASCADE;
-- DROP TABLE IF EXISTS public.board_posts     CASCADE;
-- DROP TABLE IF EXISTS public.boards          CASCADE;
