
-- ==============================================================
-- 20260701000016_estimate_enhance.sql
-- ==============================================================
-- 견적서 고도화: 견적번호(자동 채번) + 발행일 + 계약조건/특약사항
-- (대시보드/칸반/캘린더 필터/통계 기간필터/CSV 내보내기는 기존 테이블만 조회하므로 스키마 변경 없음)

-- 1) 컬럼 추가
ALTER TABLE public.estimates ADD COLUMN IF NOT EXISTS estimate_no TEXT;
ALTER TABLE public.estimates ADD COLUMN IF NOT EXISTS issue_date DATE DEFAULT CURRENT_DATE;
ALTER TABLE public.estimates ADD COLUMN IF NOT EXISTS terms TEXT;   -- 계약 조건 / 특약사항

-- 2) 견적번호 채번용 시퀀스 (타입 접두어 + 연도 + 4자리 일련번호)
CREATE SEQUENCE IF NOT EXISTS public.estimates_no_seq;

CREATE OR REPLACE FUNCTION public.set_estimate_no()
RETURNS TRIGGER AS $$
DECLARE prefix TEXT;
BEGIN
  IF NEW.estimate_no IS NULL OR NEW.estimate_no = '' THEN
    prefix := CASE NEW.type
      WHEN 'construction' THEN 'SG'   -- 시공
      WHEN 'rental' THEN 'RT'         -- 렌탈
      WHEN 'dj' THEN 'DJ'             -- DJ 프리랜서
      ELSE 'ES' END;
    NEW.estimate_no := prefix || '-'
      || to_char(COALESCE(NEW.issue_date, CURRENT_DATE), 'YYYY') || '-'
      || lpad(nextval('public.estimates_no_seq')::text, 4, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_estimates_no ON public.estimates;
CREATE TRIGGER trg_estimates_no BEFORE INSERT ON public.estimates
  FOR EACH ROW EXECUTE PROCEDURE public.set_estimate_no();

-- 3) 기존 데이터 백필 (발행일 = 작성일, 견적번호 = 채번)
UPDATE public.estimates SET issue_date = created_at::date WHERE issue_date IS NULL;

DO $$
DECLARE r RECORD; pfx TEXT;
BEGIN
  FOR r IN SELECT id, type, created_at FROM public.estimates WHERE estimate_no IS NULL ORDER BY id LOOP
    pfx := CASE r.type WHEN 'construction' THEN 'SG' WHEN 'rental' THEN 'RT' WHEN 'dj' THEN 'DJ' ELSE 'ES' END;
    UPDATE public.estimates
      SET estimate_no = pfx || '-' || to_char(r.created_at, 'YYYY') || '-' || lpad(nextval('public.estimates_no_seq')::text, 4, '0')
      WHERE id = r.id;
  END LOOP;
END $$;

-- 4) 견적번호 유니크 인덱스
CREATE UNIQUE INDEX IF NOT EXISTS uq_estimates_no ON public.estimates (estimate_no);

-- 5) 시퀀스 사용 권한 (RLS INSERT 시 트리거가 nextval 호출)
GRANT USAGE, SELECT ON SEQUENCE public.estimates_no_seq TO authenticated;

-- ==============================================================
-- 20260701000017_admin_notices.sql
-- ==============================================================
-- 사내 공지사항 (관리자 대시보드 상단 노출)
CREATE TABLE IF NOT EXISTS public.admin_notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,   -- 상단 고정
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW())
);
CREATE INDEX IF NOT EXISTS idx_admin_notices_created ON public.admin_notices (pinned DESC, created_at DESC);

DROP TRIGGER IF EXISTS trg_admin_notices_updated ON public.admin_notices;
CREATE TRIGGER trg_admin_notices_updated BEFORE UPDATE ON public.admin_notices
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.admin_notices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "admin_notices admin" ON public.admin_notices;
CREATE POLICY "admin_notices admin" ON public.admin_notices FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT ALL ON public.admin_notices TO authenticated;

-- ==============================================================
-- 20260701000018_rental_shipments.sql
-- ==============================================================
-- 렌탈 출고 현황 (계약 후 실제 출고 관리 · 사용자 마이페이지 노출)
CREATE TABLE IF NOT EXISTS public.rental_shipments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT,                         -- 연결된 렌탈 주문(선택)
  contract_id BIGINT,                      -- 연결된 계약서(선택)
  product_name TEXT NOT NULL,
  brand_name TEXT,
  quantity INTEGER NOT NULL DEFAULT 1,
  customer_name TEXT,
  customer_phone TEXT,
  ship_date DATE,                          -- 출고일
  return_date DATE,                        -- 회수 예정일
  tracking_no TEXT,                        -- 송장/추적 번호
  status TEXT NOT NULL DEFAULT 'preparing' CHECK (status IN ('preparing','shipped','delivering','installed','returned')),
  memo TEXT,
  owner_user_id UUID,                      -- 마이페이지 노출 대상(사용자)
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_rental_shipments_ship ON public.rental_shipments (ship_date DESC);
CREATE INDEX IF NOT EXISTS idx_rental_shipments_owner ON public.rental_shipments (owner_user_id);

DROP TRIGGER IF EXISTS trg_rental_shipments_updated ON public.rental_shipments;
CREATE TRIGGER trg_rental_shipments_updated BEFORE UPDATE ON public.rental_shipments
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.rental_shipments ENABLE ROW LEVEL SECURITY;
-- 관리자: 전체 관리
DROP POLICY IF EXISTS "rental_shipments admin" ON public.rental_shipments;
CREATE POLICY "rental_shipments admin" ON public.rental_shipments FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- 사용자: 본인 소유 출고 건만 조회 (마이페이지)
DROP POLICY IF EXISTS "rental_shipments owner read" ON public.rental_shipments;
CREATE POLICY "rental_shipments owner read" ON public.rental_shipments FOR SELECT TO authenticated USING (owner_user_id = auth.uid());
GRANT ALL ON public.rental_shipments TO authenticated;

-- ==============================================================
-- 20260701000019_approval_requests.sql
-- ==============================================================
-- 통합 승인 요청 (문의/신청 → 계약서·견적서 발송 → 사용자 마이페이지 승인 → 관리자 최종 처리)
CREATE TABLE IF NOT EXISTS public.approval_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref_type TEXT NOT NULL CHECK (ref_type IN ('rental_order','rental_purchase','dj_artist','construction_inquiry','dj_event')),
  ref_id BIGINT NOT NULL,                 -- 원본 엔티티 id
  title TEXT NOT NULL,                    -- 사용자에게 표시되는 제목
  doc_type TEXT NOT NULL DEFAULT 'none' CHECK (doc_type IN ('estimate','contract','none')),
  doc_id BIGINT,                          -- estimates.id 또는 contracts.id
  owner_user_id UUID NOT NULL,            -- 승인 주체(회원). 마이페이지 노출/승인 대상
  customer_name TEXT,
  amount NUMERIC,
  status TEXT NOT NULL DEFAULT 'sent' CHECK (status IN ('sent','approved','rejected','cancelled')),
  user_memo TEXT,                         -- 사용자 승인/거절 사유
  acted_at TIMESTAMPTZ,                   -- 사용자 조치 시각
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW())
);
CREATE INDEX IF NOT EXISTS idx_approval_ref ON public.approval_requests (ref_type, ref_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_approval_owner ON public.approval_requests (owner_user_id, status);

DROP TRIGGER IF EXISTS trg_approval_requests_updated ON public.approval_requests;
CREATE TRIGGER trg_approval_requests_updated BEFORE UPDATE ON public.approval_requests
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.approval_requests ENABLE ROW LEVEL SECURITY;

-- 관리자: 전체 관리 (기존 어드민 테이블과 동일 정책)
DROP POLICY IF EXISTS "approval admin" ON public.approval_requests;
CREATE POLICY "approval admin" ON public.approval_requests FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 사용자: 본인에게 온 승인 요청 조회 + 승인/거절(업데이트)
DROP POLICY IF EXISTS "approval owner read" ON public.approval_requests;
CREATE POLICY "approval owner read" ON public.approval_requests FOR SELECT TO authenticated USING (owner_user_id = auth.uid());
DROP POLICY IF EXISTS "approval owner update" ON public.approval_requests;
CREATE POLICY "approval owner update" ON public.approval_requests FOR UPDATE TO authenticated
  USING (owner_user_id = auth.uid()) WITH CHECK (owner_user_id = auth.uid());

GRANT ALL ON public.approval_requests TO authenticated;

-- ==============================================================
-- 20260701000020_user_lookup.sql
-- ==============================================================
-- 이메일 → 가입 계정(auth.users) 조회 RPC (승인 요청 발송 시 신청자 이메일로 자동 매칭)
-- SECURITY DEFINER: auth.users 접근을 위해 정의자 권한으로 실행. 이메일 완전일치 1건만 반환
CREATE OR REPLACE FUNCTION public.lookup_user_by_email(p_email TEXT)
RETURNS TABLE(id UUID, email TEXT, name TEXT)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT u.id, u.email::text, COALESCE(u.raw_user_meta_data->>'name', '')::text AS name
  FROM auth.users u
  WHERE lower(u.email) = lower(trim(p_email))
  LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION public.lookup_user_by_email(TEXT) TO authenticated;

-- ==============================================================
-- 20260701000021_dj_subscriptions.sql
-- ==============================================================
-- DJ 아티스트 구독(프리미엄) — 유료 구독 시 중개료 면제 + 상위 노출 + 프리미엄 섹션 노출
ALTER TABLE public.dj_artists ADD COLUMN IF NOT EXISTS subscription_plan TEXT NOT NULL DEFAULT 'free' CHECK (subscription_plan IN ('free','premium'));
ALTER TABLE public.dj_artists ADD COLUMN IF NOT EXISTS subscription_started DATE;   -- 구독 시작일
ALTER TABLE public.dj_artists ADD COLUMN IF NOT EXISTS subscription_until DATE;     -- 구독 만료일(NULL=무기한)
ALTER TABLE public.dj_artists ADD COLUMN IF NOT EXISTS subscription_fee NUMERIC;    -- 구독료(원)
ALTER TABLE public.dj_artists ADD COLUMN IF NOT EXISTS birth_year INTEGER;          -- 연령 통계용(출생연도)

CREATE INDEX IF NOT EXISTS idx_dj_artists_subscription ON public.dj_artists (subscription_plan, subscription_until);

-- ==============================================================
-- 20260701000022_subscription_tiers.sql
-- ==============================================================
-- 구독 티어(등급) 카탈로그 — 구독료·기간·중개료·혜택 정의
CREATE TABLE IF NOT EXISTS public.subscription_tiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,                                    -- 티어명 (예: 프리미엄, VIP)
  price NUMERIC NOT NULL DEFAULT 0,                      -- 구독료(원)
  period_months INTEGER NOT NULL DEFAULT 1,              -- 구독 기간(개월)
  commission_rate NUMERIC NOT NULL DEFAULT 0,            -- 중개료율(%). 0 = 면제
  priority_boost BOOLEAN NOT NULL DEFAULT TRUE,          -- 상위 노출 혜택
  premium_section BOOLEAN NOT NULL DEFAULT TRUE,         -- 프리미엄 DJ 섹션 노출
  color TEXT NOT NULL DEFAULT '#7c3aed',                 -- 배지 색상
  description TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_subscription_tiers_order ON public.subscription_tiers (display_order);

DROP TRIGGER IF EXISTS trg_subscription_tiers_updated ON public.subscription_tiers;
CREATE TRIGGER trg_subscription_tiers_updated BEFORE UPDATE ON public.subscription_tiers
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.subscription_tiers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "subscription_tiers admin" ON public.subscription_tiers;
CREATE POLICY "subscription_tiers admin" ON public.subscription_tiers FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- 공개 조회(구독 안내 페이지 등에서 활성 티어 노출)
DROP POLICY IF EXISTS "subscription_tiers public read" ON public.subscription_tiers;
CREATE POLICY "subscription_tiers public read" ON public.subscription_tiers FOR SELECT TO anon, authenticated USING (is_active = true);
GRANT ALL ON public.subscription_tiers TO authenticated;
GRANT SELECT ON public.subscription_tiers TO anon;

-- 기본 티어 시드 (무료: 중개료 5% / 프리미엄: 면제·혜택)
INSERT INTO public.subscription_tiers (name, price, period_months, commission_rate, priority_boost, premium_section, color, description, display_order)
SELECT '무료', 0, 0, 5, false, false, '#94a3b8', '기본 회원 · 수주 시 중개료 부과', 0
WHERE NOT EXISTS (SELECT 1 FROM public.subscription_tiers WHERE name = '무료');

INSERT INTO public.subscription_tiers (name, price, period_months, commission_rate, priority_boost, premium_section, color, description, display_order)
SELECT '프리미엄', 9900, 1, 0, true, true, '#7c3aed', '중개료 면제 · 상위 노출 · 프리미엄 DJ 섹션 노출', 1
WHERE NOT EXISTS (SELECT 1 FROM public.subscription_tiers WHERE name = '프리미엄');

-- ==============================================================
-- 20260701000023_approval_docs.sql
-- ==============================================================
-- 승인 요청에 견적서·계약서를 각각(동시) 첨부 — 발송 서류 다중화
ALTER TABLE public.approval_requests ADD COLUMN IF NOT EXISTS estimate_id BIGINT;   -- 첨부 견적서(estimates.id)
ALTER TABLE public.approval_requests ADD COLUMN IF NOT EXISTS contract_id BIGINT;   -- 첨부 계약서(contracts.id)

-- ==============================================================
-- 20260701000024_rental_product_pricing.sql
-- ==============================================================
-- 렌탈 상품 가격 고도화: 정가(취소선) + 쿠폰 적용가 (상세페이지 할인율 표시용)
-- 할인율은 저장하지 않고 (list_price - daily_price) / list_price 로 화면에서 계산
ALTER TABLE public.rental_products ADD COLUMN IF NOT EXISTS list_price NUMERIC;    -- 정가(할인 전 일 단가, 취소선). NULL/0 = 할인 표시 안 함
ALTER TABLE public.rental_products ADD COLUMN IF NOT EXISTS coupon_price NUMERIC;  -- 쿠폰 적용가(일 단가). NULL/0 = 쿠폰 표시 안 함

-- ==============================================================
-- 20260701000025_dj_guarantees.sql
-- ==============================================================
-- DJ 아티스트: 전국 지역별 게런티 맵 (기존 서울/경기/대전 컬럼은 호환용 유지)
ALTER TABLE public.dj_artists ADD COLUMN IF NOT EXISTS guarantees JSONB NOT NULL DEFAULT '{}'::jsonb;

-- ==============================================================
-- 20260701000026_storage_pdf.sql  (권장)
-- ==============================================================
-- DJ 서류/포트폴리오 PDF 업로드 허용 — 스토리지 버킷 허용 형식에 application/pdf 추가
UPDATE storage.buckets
SET allowed_mime_types = ARRAY['image/jpeg','image/png','image/webp','image/gif','image/avif','application/pdf']
WHERE id = 'construction';

-- ==============================================================
-- 20260701000027_rental_purchase_sell.sql
-- ==============================================================
-- 판매(중고 매입) 신청 고도화: 상품 상세 '판매하기' → 회원 전용 · 상품/카테고리 자동 기입 + 신청 회원 연결
ALTER TABLE public.rental_purchase_inquiries
  ADD COLUMN IF NOT EXISTS category_name        TEXT,  -- 2차(소) 카테고리
  ADD COLUMN IF NOT EXISTS parent_category_name TEXT,  -- 1차(대) 카테고리
  ADD COLUMN IF NOT EXISTS owner_user_id        UUID;  -- 판매 신청 회원(auth.users.id)

CREATE INDEX IF NOT EXISTS idx_rental_purchase_owner ON public.rental_purchase_inquiries (owner_user_id);

-- ==============================================================
-- 20260701000028_rental_brand_favorites.sql
-- ==============================================================
-- 브랜드 관심 저장(회원별) — 브랜드 페이지 "관심 N + 저장한 회원" 표시
--  · 누구나 조회, 저장/해제는 로그인 회원 본인만 · user_name 은 표시용 스냅샷
CREATE TABLE IF NOT EXISTS public.rental_brand_favorites (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id   BIGINT NOT NULL REFERENCES public.rental_brands(id) ON DELETE CASCADE,
  user_id    UUID   NOT NULL,
  user_name  TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (brand_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_rbf_brand ON public.rental_brand_favorites (brand_id);
CREATE INDEX IF NOT EXISTS idx_rbf_user  ON public.rental_brand_favorites (user_id);

ALTER TABLE public.rental_brand_favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "rbf read"   ON public.rental_brand_favorites;
DROP POLICY IF EXISTS "rbf insert" ON public.rental_brand_favorites;
DROP POLICY IF EXISTS "rbf delete" ON public.rental_brand_favorites;

CREATE POLICY "rbf read"   ON public.rental_brand_favorites FOR SELECT USING (true);
CREATE POLICY "rbf insert" ON public.rental_brand_favorites FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "rbf delete" ON public.rental_brand_favorites FOR DELETE TO authenticated USING (user_id = auth.uid());

GRANT SELECT                 ON public.rental_brand_favorites TO anon;
GRANT SELECT, INSERT, DELETE ON public.rental_brand_favorites TO authenticated;

-- ==============================================================
-- 20260701000029_rental_sales_count_fn.sql
-- ==============================================================
-- 렌탈 베스트/인기 정렬용: 상품별 판매수량 집계 (결제완료 기준)
-- rental_orders 는 고객 PII 를 포함해 anon SELECT 를 막아둠(→ 공개 페이지에서 401).
-- PII 없이 집계값만 돌려주는 SECURITY DEFINER 함수로 공개하여 인기순 정렬에 사용한다.
CREATE OR REPLACE FUNCTION public.rental_sales_count()
RETURNS TABLE (product_id BIGINT, qty BIGINT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT product_id, SUM(quantity)::BIGINT AS qty
  FROM public.rental_orders
  WHERE payment_status = 'paid' AND product_id IS NOT NULL
  GROUP BY product_id;
$$;

GRANT EXECUTE ON FUNCTION public.rental_sales_count() TO anon, authenticated;

-- ==============================================================
-- 20260701000030_rental_product_detail_html.sql
-- ==============================================================
-- 렌탈 상품 "상품 상세" 콘텐츠: 상품 이미지(갤러리)와 별개로, HTML 에디터로 작성하는 상세 본문(이미지 포함)
-- 상세페이지 '상세' 탭에 렌더링. 비어있으면 상세 탭/섹션 숨김.
ALTER TABLE public.rental_products ADD COLUMN IF NOT EXISTS detail_html TEXT;

-- ==============================================================
-- 20260701000031_perf_indexes.sql
-- ==============================================================
-- 성능 튜닝: 자주 필터/정렬되는 컬럼에 인덱스 추가 (모두 IF NOT EXISTS · 추가 전용, 데이터 변경 없음)
CREATE INDEX IF NOT EXISTS idx_news_active_created   ON public.news (is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_category_created ON public.news (category_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rental_brands_active     ON public.rental_brands (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_rental_categories_active ON public.rental_categories (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_con_companies_active ON public.construction_companies (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_con_works_status_sched ON public.construction_works (status, scheduled_start);

-- ==============================================================
-- 20260701000032_enable_rls_legacy_tables.sql
-- ==============================================================
-- 보안: 레거시 미사용 테이블 RLS 활성화(정책 없음=전면 차단, service_role 만 접근)
ALTER TABLE public.admin_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_logs  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.popups      ENABLE ROW LEVEL SECURITY;
