-- =====================================================================
-- Klipse — 최신 기능 통합 실행 SQL (한 번에 실행)
-- 포함: 공통 트리거 함수 + DJ 입점 + 약관 + 시공 업무/업체 + 견적서
--       + DJ 행사 문의 + 계약서
-- 모두 IF NOT EXISTS / OR REPLACE 로 idempotent (여러 번 실행 안전)
-- =====================================================================

-- 0) 공통: updated_at 자동 갱신 트리거 함수
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- 1) DJ 입점(아티스트 회원)
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.dj_artists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, stage_name TEXT, phone TEXT, email TEXT,
  id_card_url TEXT, bankbook_url TEXT, resume_url TEXT,
  portfolio_type TEXT NOT NULL DEFAULT 'img' CHECK (portfolio_type IN ('pdf','img')),
  portfolio_files JSONB NOT NULL DEFAULT '[]'::jsonb,
  soundcloud_url TEXT, mp3_url TEXT, youtube_url TEXT,
  social_links JSONB NOT NULL DEFAULT '[]'::jsonb,
  regions JSONB NOT NULL DEFAULT '[]'::jsonb,
  guarantee_seoul NUMERIC, guarantee_gyeonggi NUMERIC, guarantee_daejeon NUMERIC,
  guarantees JSONB NOT NULL DEFAULT '{}'::jsonb,
  intro TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','hold','rejected')),
  admin_memo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), updated_by TEXT
);
-- 기존 테이블에도 전국 지역별 게런티 맵 컬럼 보강
ALTER TABLE public.dj_artists ADD COLUMN IF NOT EXISTS guarantees JSONB NOT NULL DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_dj_artists_status ON public.dj_artists (status, created_at DESC);
DROP TRIGGER IF EXISTS trg_dj_artists_updated ON public.dj_artists;
CREATE TRIGGER trg_dj_artists_updated BEFORE UPDATE ON public.dj_artists FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
ALTER TABLE public.dj_artists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "dj insert" ON public.dj_artists;
DROP POLICY IF EXISTS "dj admin"  ON public.dj_artists;
CREATE POLICY "dj insert" ON public.dj_artists FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "dj admin"  ON public.dj_artists FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT INSERT ON public.dj_artists TO anon;
GRANT ALL    ON public.dj_artists TO authenticated;

-- =====================================================================
-- 2) 약관 관리 (서비스 이용약관 / 개인정보 처리방침)
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.terms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('service','privacy')),
  title TEXT NOT NULL, content TEXT NOT NULL DEFAULT '',
  version TEXT, effective_date DATE,
  display_order INTEGER NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_terms_type ON public.terms (type, display_order);
DROP TRIGGER IF EXISTS trg_terms_updated ON public.terms;
CREATE TRIGGER trg_terms_updated BEFORE UPDATE ON public.terms FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
ALTER TABLE public.terms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "terms read"  ON public.terms;
DROP POLICY IF EXISTS "terms admin" ON public.terms;
CREATE POLICY "terms read"  ON public.terms FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "terms admin" ON public.terms FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT ON public.terms TO anon;
GRANT ALL    ON public.terms TO authenticated;

-- =====================================================================
-- 3) 시공 업무 관리(업체/업무) + 견적서(시공/렌탈/DJ)
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.construction_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, manager TEXT, phone TEXT, email TEXT, region TEXT, memo TEXT,
  display_order INTEGER NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), created_by TEXT, updated_by TEXT
);
CREATE TABLE IF NOT EXISTS public.construction_works (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_id BIGINT, title TEXT NOT NULL, customer_name TEXT, customer_phone TEXT,
  company_id BIGINT REFERENCES public.construction_companies(id) ON DELETE SET NULL, company_name TEXT, assignee TEXT,
  scheduled_start DATE, scheduled_end DATE, amount NUMERIC,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','assigned','in_progress','done','hold')),
  memo TEXT, display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_con_works_sched ON public.construction_works (scheduled_start);
CREATE TABLE IF NOT EXISTS public.estimates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('construction','rental','dj')),
  title TEXT NOT NULL, customer_name TEXT, customer_phone TEXT, customer_email TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  subtotal NUMERIC NOT NULL DEFAULT 0, discount NUMERIC NOT NULL DEFAULT 0, tax NUMERIC NOT NULL DEFAULT 0, total NUMERIC NOT NULL DEFAULT 0,
  valid_until DATE, status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','accepted','rejected')),
  memo TEXT, display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_estimates_type ON public.estimates (type, created_at DESC);

-- =====================================================================
-- 4) DJ 행사(섭외) 문의
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.dj_event_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  customer_name TEXT, customer_phone TEXT, customer_email TEXT,
  event_date DATE, event_time TEXT, region TEXT, venue TEXT, budget NUMERIC,
  artist_id BIGINT REFERENCES public.dj_artists(id) ON DELETE SET NULL, artist_name TEXT, guests INTEGER,
  message TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','consulting','confirmed','done','cancelled')),
  admin_memo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_dj_events_date ON public.dj_event_inquiries (event_date);
CREATE INDEX IF NOT EXISTS idx_dj_events_status ON public.dj_event_inquiries (status, created_at DESC);
DROP TRIGGER IF EXISTS trg_dj_events_updated ON public.dj_event_inquiries;
CREATE TRIGGER trg_dj_events_updated BEFORE UPDATE ON public.dj_event_inquiries FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
ALTER TABLE public.dj_event_inquiries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "dj ev insert" ON public.dj_event_inquiries;
DROP POLICY IF EXISTS "dj ev admin"  ON public.dj_event_inquiries;
CREATE POLICY "dj ev insert" ON public.dj_event_inquiries FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "dj ev admin"  ON public.dj_event_inquiries FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT INSERT ON public.dj_event_inquiries TO anon;
GRANT ALL    ON public.dj_event_inquiries TO authenticated;

-- =====================================================================
-- 5) 계약서(문서) 관리
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template TEXT NOT NULL CHECK (template IN ('freelancer','construction_order','event_order','rental_handover','rental')),
  title TEXT NOT NULL, customer_name TEXT,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','completed')),
  inquiry_id BIGINT, owner_user_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_contracts_template ON public.contracts (template, created_at DESC);
DROP TRIGGER IF EXISTS trg_contracts_updated ON public.contracts;
CREATE TRIGGER trg_contracts_updated BEFORE UPDATE ON public.contracts FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "contracts admin" ON public.contracts;
DROP POLICY IF EXISTS "contracts owner read" ON public.contracts;
CREATE POLICY "contracts admin" ON public.contracts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "contracts owner read" ON public.contracts FOR SELECT TO authenticated USING (owner_user_id = auth.uid());
GRANT ALL ON public.contracts TO authenticated;

-- =====================================================================
-- 6) 시공 업무/업체/견적서 트리거 + RLS (관리자 전용)
-- =====================================================================
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['construction_companies','construction_works','estimates'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_updated ON public.%I;', t, t);
    EXECUTE format('CREATE TRIGGER trg_%s_updated BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();', t, t);
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('DROP POLICY IF EXISTS "%s admin" ON public.%I;', t, t);
    EXECUTE format('CREATE POLICY "%s admin" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true);', t, t);
    EXECUTE format('GRANT ALL ON public.%I TO authenticated;', t);
  END LOOP;
END $$;

-- =====================================================================
-- 7) (권장) 스토리지 버킷 PDF 업로드 허용 — DJ 포트폴리오/서류 PDF
-- =====================================================================
UPDATE storage.buckets
SET allowed_mime_types = ARRAY['image/jpeg','image/png','image/webp','image/gif','image/avif','application/pdf']
WHERE id = 'construction';

-- 완료. (오류 없이 실행되면 최신 기능 테이블이 모두 준비됩니다)
