-- =============================================================
-- 메인 비주얼 관리 (시공/렌탈/DJ 섹션별 메인 배너 통합 관리)
--  - section: construction | rental | dj
--  - display_order(순번), is_active(활성화), 감사 컬럼 포함
-- =============================================================

-- updated_at 자동 갱신 공용 함수 (이미 있으면 대체)
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS public.main_visual_banners (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section       TEXT NOT NULL CHECK (section IN ('construction', 'rental', 'dj')),
  image_url     TEXT,
  badge         TEXT,
  title         TEXT NOT NULL,
  subtitle      TEXT,
  cta_text      TEXT,
  link_url      TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

DROP TRIGGER IF EXISTS trg_main_visual_banners_updated ON public.main_visual_banners;
CREATE TRIGGER trg_main_visual_banners_updated
  BEFORE UPDATE ON public.main_visual_banners
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.main_visual_banners ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "mvb public read" ON public.main_visual_banners;
DROP POLICY IF EXISTS "mvb admin all"   ON public.main_visual_banners;
CREATE POLICY "mvb public read" ON public.main_visual_banners FOR SELECT USING (true);
CREATE POLICY "mvb admin all"   ON public.main_visual_banners FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT ON public.main_visual_banners TO anon;
GRANT ALL    ON public.main_visual_banners TO authenticated;
