-- DJ 입점(아티스트 회원) 신청
CREATE TABLE IF NOT EXISTS public.dj_artists (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  stage_name      TEXT,                                   -- 활동명
  phone           TEXT,
  email           TEXT,
  id_card_url     TEXT,                                   -- 신분증
  bankbook_url    TEXT,                                   -- 통장사본
  resume_url      TEXT,                                   -- 이력서
  portfolio_type  TEXT NOT NULL DEFAULT 'img' CHECK (portfolio_type IN ('pdf', 'img')),
  portfolio_files JSONB NOT NULL DEFAULT '[]'::jsonb,     -- 포트폴리오 파일(url 배열)
  soundcloud_url  TEXT,
  mp3_url         TEXT,
  youtube_url     TEXT,
  social_links    JSONB NOT NULL DEFAULT '[]'::jsonb,     -- [{ label, url }]
  regions         JSONB NOT NULL DEFAULT '[]'::jsonb,     -- ['서울','경기도','대전']
  guarantee_seoul     NUMERIC,
  guarantee_gyeonggi  NUMERIC,
  guarantee_daejeon   NUMERIC,
  intro           TEXT,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'hold', 'rejected')),
  admin_memo      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by      TEXT
);

CREATE INDEX IF NOT EXISTS idx_dj_artists_status ON public.dj_artists (status, created_at DESC);

DROP TRIGGER IF EXISTS trg_dj_artists_updated ON public.dj_artists;
CREATE TRIGGER trg_dj_artists_updated BEFORE UPDATE ON public.dj_artists
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.dj_artists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "dj insert" ON public.dj_artists;
DROP POLICY IF EXISTS "dj admin"  ON public.dj_artists;
CREATE POLICY "dj insert" ON public.dj_artists FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "dj admin"  ON public.dj_artists FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT INSERT ON public.dj_artists TO anon;
GRANT ALL    ON public.dj_artists TO authenticated;
