-- =============================================================
-- 메인 비주얼 관리 (시공/렌탈/DJ 섹션별 메인 배너 통합 관리)
--  · 기존 main_visuals 테이블은 폐기하고 새 구조로 재설계
--  · section : construction | rental | dj
--  · type    : type_a(기본) | type_b(쿠폰형 - 배지 + 버튼)
--  · display_order(순번), is_active(활성화), 감사 컬럼 포함
-- =============================================================

-- 1) 레거시 테이블 제거 (기존 메인 비주얼 DB 폐기)
DROP TABLE IF EXISTS public.main_visuals CASCADE;
DROP TABLE IF EXISTS public.main_visual_banners CASCADE;

-- 2) updated_at 자동 갱신 공용 함수 (이미 있으면 대체)
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3) 새 테이블
CREATE TABLE public.main_visual_banners (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section       TEXT NOT NULL CHECK (section IN ('construction', 'rental', 'dj')),
  type          TEXT NOT NULL DEFAULT 'type_a' CHECK (type IN ('type_a', 'type_b')),
  is_ad         BOOLEAN NOT NULL DEFAULT false,        -- 시공 AD 배너 여부
  image_url     TEXT,
  image_mobile_url TEXT,                                -- AD 모바일(가로) 이미지
  badge         TEXT,                 -- type_b 전용 (쿠폰/세일 배지)
  title         TEXT NOT NULL,        -- 줄바꿈 허용
  subtitle      TEXT,
  cta_text      TEXT,                 -- type_b 전용 (쿠폰 버튼 문구)
  link_url      TEXT,
  author_name   TEXT,                 -- 클라이언트 표시 등록자명
  author_avatar TEXT,                 -- 등록자 아바타
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

CREATE INDEX idx_mvb_section_active ON public.main_visual_banners (section, is_active, display_order);

CREATE TRIGGER trg_main_visual_banners_updated
  BEFORE UPDATE ON public.main_visual_banners
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- 4) RLS (공개 읽기 / 인증 사용자 전체 권한)
ALTER TABLE public.main_visual_banners ENABLE ROW LEVEL SECURITY;
CREATE POLICY "mvb public read" ON public.main_visual_banners FOR SELECT USING (true);
CREATE POLICY "mvb admin all"   ON public.main_visual_banners FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT ON public.main_visual_banners TO anon;
GRANT ALL    ON public.main_visual_banners TO authenticated;

-- 5) 샘플 데이터 (선택) ------------------------------------------------
INSERT INTO public.main_visual_banners (section, type, image_url, badge, title, subtitle, cta_text, link_url, display_order, created_by, updated_by) VALUES
  ('construction', 'type_a', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&q=80&auto=format&fit=crop', NULL, E'공간을 바꾸는\nKlipse 시공', '검증된 시공팀과 함께하는 프리미엄 인테리어', NULL, NULL, 0, 'system', 'system'),
  ('construction', 'type_b', 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&q=80&auto=format&fit=crop', '상담 이벤트', '무료 방문 견적', '지금 신청하면 시공 상담 무료', '시공 문의하기', '/construction-inquiry', 1, 'system', 'system'),
  ('rental', 'type_a', 'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=900&q=80&auto=format&fit=crop', NULL, E'거실부터\n다이닝까지, 피아바', '하나의 취향으로 완성하는 라이프스타일 컬렉션', NULL, NULL, 0, 'system', 'system'),
  ('rental', 'type_b', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=900&q=80&auto=format&fit=crop', '빈백 특가 세일', '요기보 최대 44%', '최대 27만원 할인', '브랜드쿠폰 최대 20%', NULL, 1, 'system', 'system');
