-- 환경설정: 부서 / 부서별 접근권한 / 관리자(프로필)
-- 부서
CREATE TABLE IF NOT EXISTS public.departments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  menu_keys  JSONB NOT NULL DEFAULT '[]'::jsonb,  -- 접근 허용 어드민 메뉴 키 배열
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW())
);

DROP TRIGGER IF EXISTS trg_departments_updated ON public.departments;
CREATE TRIGGER trg_departments_updated BEFORE UPDATE ON public.departments
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- 관리자(프로필) 보강: Supabase Auth 연결 + 부서 + 희망 이메일
ALTER TABLE public.admins
  ADD COLUMN IF NOT EXISTS auth_user_id  UUID,
  ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES public.departments(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS desired_email TEXT;

-- RLS (관리자 전용 데이터: 로그인된 관리자만)
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins      ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "dept admin" ON public.departments;
CREATE POLICY "dept admin" ON public.departments FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "admins admin" ON public.admins;
CREATE POLICY "admins admin" ON public.admins FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT ALL ON public.departments TO authenticated;
GRANT ALL ON public.admins TO authenticated;
