-- =============================================================
-- 렌탈 관리: 브랜드 → 카테고리 → 상품
--  · 가격: 일일 단가(daily_price) × 대여일수 (주문 시 계산)
--  · 보증금(deposit), 재고(stock), 최소/최대 대여기간(min/max_days), 배송·설치비(delivery_fee)
--  · 상품 옵션(options jsonb): [{ name, add_price }]
-- =============================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 0-1) 재실행 안전: 기존 부분 생성분 정리
DROP TABLE IF EXISTS public.rental_purchase_inquiries CASCADE;
DROP TABLE IF EXISTS public.rental_orders             CASCADE;
DROP TABLE IF EXISTS public.rental_products           CASCADE;
DROP TABLE IF EXISTS public.rental_categories         CASCADE;
DROP TABLE IF EXISTS public.rental_brands             CASCADE;

-- 1) 브랜드 ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.rental_brands (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  logo_url      TEXT,
  description   TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

-- 2) 카테고리 (브랜드 소속) ------------------------------------------
CREATE TABLE IF NOT EXISTS public.rental_categories (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id      BIGINT REFERENCES public.rental_brands(id) ON DELETE CASCADE,
  parent_id     BIGINT REFERENCES public.rental_categories(id) ON DELETE CASCADE,  -- 2Depth 상위
  name          TEXT NOT NULL,
  description   TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

-- 3) 상품 (브랜드 + 카테고리 소속) -----------------------------------
CREATE TABLE IF NOT EXISTS public.rental_products (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id      BIGINT REFERENCES public.rental_brands(id) ON DELETE SET NULL,
  category_id   BIGINT REFERENCES public.rental_categories(id) ON DELETE SET NULL,
  name          TEXT NOT NULL,
  description   TEXT,                                  -- 상품 설명(HTML 허용)
  thumbnail_url TEXT,
  images        JSONB NOT NULL DEFAULT '[]'::jsonb,    -- 추가 이미지 URL 배열
  daily_price   NUMERIC NOT NULL DEFAULT 0,            -- 일일 단가
  deposit       NUMERIC NOT NULL DEFAULT 0,            -- 보증금
  delivery_fee  NUMERIC NOT NULL DEFAULT 0,            -- 배송/설치비
  stock         INTEGER NOT NULL DEFAULT 0,            -- 재고 수량
  min_days      INTEGER NOT NULL DEFAULT 1,            -- 최소 대여일
  max_days      INTEGER,                               -- 최대 대여일(NULL=무제한)
  options       JSONB NOT NULL DEFAULT '[]'::jsonb,    -- [{ name, add_price }]
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  is_exclusive  BOOLEAN NOT NULL DEFAULT false,        -- 단독 상품
  is_event      BOOLEAN NOT NULL DEFAULT false,        -- 기획전
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

CREATE INDEX IF NOT EXISTS idx_rental_categories_brand ON public.rental_categories (brand_id, display_order);
CREATE INDEX IF NOT EXISTS idx_rental_products_brand_cat ON public.rental_products (brand_id, category_id, display_order);

-- updated_at 트리거
DROP TRIGGER IF EXISTS trg_rental_brands_updated ON public.rental_brands;
CREATE TRIGGER trg_rental_brands_updated BEFORE UPDATE ON public.rental_brands
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
DROP TRIGGER IF EXISTS trg_rental_categories_updated ON public.rental_categories;
CREATE TRIGGER trg_rental_categories_updated BEFORE UPDATE ON public.rental_categories
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
DROP TRIGGER IF EXISTS trg_rental_products_updated ON public.rental_products;
CREATE TRIGGER trg_rental_products_updated BEFORE UPDATE ON public.rental_products
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- RLS (공개 읽기 / 인증 사용자 전체)
ALTER TABLE public.rental_brands     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rental_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rental_products   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "rb read"  ON public.rental_brands;
DROP POLICY IF EXISTS "rb admin" ON public.rental_brands;
DROP POLICY IF EXISTS "rc read"  ON public.rental_categories;
DROP POLICY IF EXISTS "rc admin" ON public.rental_categories;
DROP POLICY IF EXISTS "rp read"  ON public.rental_products;
DROP POLICY IF EXISTS "rp admin" ON public.rental_products;

CREATE POLICY "rb read"  ON public.rental_brands     FOR SELECT USING (true);
CREATE POLICY "rb admin" ON public.rental_brands     FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "rc read"  ON public.rental_categories FOR SELECT USING (true);
CREATE POLICY "rc admin" ON public.rental_categories FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "rp read"  ON public.rental_products   FOR SELECT USING (true);
CREATE POLICY "rp admin" ON public.rental_products   FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT ON public.rental_brands, public.rental_categories, public.rental_products TO anon;
GRANT ALL    ON public.rental_brands, public.rental_categories, public.rental_products TO authenticated;

-- 4) 렌탈 주문/결제 내역 (렌탈 관리) --------------------------------
--    일반 사용자가 "몇날 몇시에 렌탈" 결제(PG)하면 적재되는 목록
CREATE TABLE IF NOT EXISTS public.rental_orders (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id     BIGINT REFERENCES public.rental_products(id) ON DELETE SET NULL,
  product_name   TEXT,                                  -- 주문 시점 스냅샷
  brand_name     TEXT,
  option_name    TEXT,
  customer_name  TEXT,
  customer_phone TEXT,
  customer_email TEXT,
  rental_start   TIMESTAMPTZ,                           -- 대여 시작(몇날 몇시)
  rental_days    INTEGER NOT NULL DEFAULT 1,
  rental_end     TIMESTAMPTZ,                           -- 반납 예정
  quantity       INTEGER NOT NULL DEFAULT 1,
  daily_price    NUMERIC NOT NULL DEFAULT 0,
  deposit        NUMERIC NOT NULL DEFAULT 0,
  delivery_fee   NUMERIC NOT NULL DEFAULT 0,
  total_amount   NUMERIC NOT NULL DEFAULT 0,            -- 결제 총액
  payment_status TEXT NOT NULL DEFAULT 'paid'  CHECK (payment_status IN ('pending','paid','cancelled','refunded')),
  payment_method TEXT,
  payment_id     TEXT,                                  -- PG 거래 ID
  order_status   TEXT NOT NULL DEFAULT 'reserved' CHECK (order_status IN ('reserved','renting','returned','cancelled')),
  memo           TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by     TEXT
);

-- 5) 렌탈 입점 문의 (중고 매입 / 입점 신청) -------------------------
--    조건/희망가 입력 → 어드민 승인/보류/반려
CREATE TABLE IF NOT EXISTS public.rental_purchase_inquiries (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      BIGINT REFERENCES public.rental_products(id) ON DELETE SET NULL, -- 기존 상품 기반(선택)
  product_name    TEXT NOT NULL,                        -- 매입 희망 품목
  brand_name      TEXT,
  condition_grade TEXT NOT NULL DEFAULT 'A' CHECK (condition_grade IN ('C','B','A','A+','A++')),
  desired_price   NUMERIC NOT NULL DEFAULT 0,           -- 매입 희망가
  images          JSONB NOT NULL DEFAULT '[]'::jsonb,
  description     TEXT,                                 -- 컨디션 설명
  applicant_name  TEXT,
  applicant_phone TEXT,
  applicant_email TEXT,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','hold','rejected')),
  admin_memo      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by      TEXT
);

CREATE INDEX IF NOT EXISTS idx_rental_orders_product ON public.rental_orders (product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rental_orders_status  ON public.rental_orders (order_status, payment_status);
CREATE INDEX IF NOT EXISTS idx_rental_purchase_status ON public.rental_purchase_inquiries (status, created_at DESC);

DROP TRIGGER IF EXISTS trg_rental_orders_updated ON public.rental_orders;
CREATE TRIGGER trg_rental_orders_updated BEFORE UPDATE ON public.rental_orders
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
DROP TRIGGER IF EXISTS trg_rental_purchase_updated ON public.rental_purchase_inquiries;
CREATE TRIGGER trg_rental_purchase_updated BEFORE UPDATE ON public.rental_purchase_inquiries
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.rental_orders             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rental_purchase_inquiries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ro insert" ON public.rental_orders;
DROP POLICY IF EXISTS "ro admin"  ON public.rental_orders;
DROP POLICY IF EXISTS "rpi insert" ON public.rental_purchase_inquiries;
DROP POLICY IF EXISTS "rpi admin"  ON public.rental_purchase_inquiries;

-- 주문/문의는 누구나 접수(INSERT), 조회·수정·삭제는 관리자(authenticated)만
CREATE POLICY "ro insert" ON public.rental_orders FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "ro admin"  ON public.rental_orders FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "rpi insert" ON public.rental_purchase_inquiries FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "rpi admin"  ON public.rental_purchase_inquiries FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT INSERT ON public.rental_orders, public.rental_purchase_inquiries TO anon;
GRANT ALL    ON public.rental_orders, public.rental_purchase_inquiries TO authenticated;
