-- DJ 행사(섭외) 문의 관리
CREATE TABLE IF NOT EXISTS public.dj_event_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,                 -- 행사명
  customer_name TEXT, customer_phone TEXT, customer_email TEXT,
  event_date DATE, event_time TEXT,
  region TEXT, venue TEXT,
  budget NUMERIC,
  artist_id BIGINT REFERENCES public.dj_artists(id) ON DELETE SET NULL,
  artist_name TEXT,                    -- 배정 DJ 스냅샷
  guests INTEGER,
  message TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','consulting','confirmed','done','cancelled')),
  admin_memo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()), updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_dj_events_date ON public.dj_event_inquiries (event_date);
CREATE INDEX IF NOT EXISTS idx_dj_events_status ON public.dj_event_inquiries (status, created_at DESC);

DROP TRIGGER IF EXISTS trg_dj_events_updated ON public.dj_event_inquiries;
CREATE TRIGGER trg_dj_events_updated BEFORE UPDATE ON public.dj_event_inquiries FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.dj_event_inquiries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "dj ev insert" ON public.dj_event_inquiries;
DROP POLICY IF EXISTS "dj ev admin"  ON public.dj_event_inquiries;
-- 공개 섭외 문의 폼(추후) 대비 anon INSERT 허용 + 관리자 전체
CREATE POLICY "dj ev insert" ON public.dj_event_inquiries FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "dj ev admin"  ON public.dj_event_inquiries FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT INSERT ON public.dj_event_inquiries TO anon;
GRANT ALL    ON public.dj_event_inquiries TO authenticated;
