-- 구독 티어(등급) 카탈로그 — 구독료·기간·중개료·혜택 정의
CREATE TABLE IF NOT EXISTS public.subscription_tiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,                                    -- 티어명 (예: 프리미엄, VIP)
  price NUMERIC NOT NULL DEFAULT 0,                      -- 구독료(원)
  period_months INTEGER NOT NULL DEFAULT 1,              -- 구독 기간(개월)
  commission_rate NUMERIC NOT NULL DEFAULT 0,            -- 중개료율(%). 0 = 면제
  priority_boost BOOLEAN NOT NULL DEFAULT TRUE,          -- 상위 노출 혜택
  premium_section BOOLEAN NOT NULL DEFAULT TRUE,         -- 프리미엄 DJ 섹션 노출
  color TEXT NOT NULL DEFAULT '#7c3aed',                 -- 배지 색상
  description TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_subscription_tiers_order ON public.subscription_tiers (display_order);

DROP TRIGGER IF EXISTS trg_subscription_tiers_updated ON public.subscription_tiers;
CREATE TRIGGER trg_subscription_tiers_updated BEFORE UPDATE ON public.subscription_tiers
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.subscription_tiers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "subscription_tiers admin" ON public.subscription_tiers;
CREATE POLICY "subscription_tiers admin" ON public.subscription_tiers FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- 공개 조회(구독 안내 페이지 등에서 활성 티어 노출)
DROP POLICY IF EXISTS "subscription_tiers public read" ON public.subscription_tiers;
CREATE POLICY "subscription_tiers public read" ON public.subscription_tiers FOR SELECT TO anon, authenticated USING (is_active = true);
GRANT ALL ON public.subscription_tiers TO authenticated;
GRANT SELECT ON public.subscription_tiers TO anon;

-- 기본 티어 시드 (무료: 중개료 5% / 프리미엄: 면제·혜택)
INSERT INTO public.subscription_tiers (name, price, period_months, commission_rate, priority_boost, premium_section, color, description, display_order)
SELECT '무료', 0, 0, 5, false, false, '#94a3b8', '기본 회원 · 수주 시 중개료 부과', 0
WHERE NOT EXISTS (SELECT 1 FROM public.subscription_tiers WHERE name = '무료');

INSERT INTO public.subscription_tiers (name, price, period_months, commission_rate, priority_boost, premium_section, color, description, display_order)
SELECT '프리미엄', 9900, 1, 0, true, true, '#7c3aed', '중개료 면제 · 상위 노출 · 프리미엄 DJ 섹션 노출', 1
WHERE NOT EXISTS (SELECT 1 FROM public.subscription_tiers WHERE name = '프리미엄');
