-- 통합 승인 요청 (문의/신청 → 계약서·견적서 발송 → 사용자 마이페이지 승인 → 관리자 최종 처리)
CREATE TABLE IF NOT EXISTS public.approval_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref_type TEXT NOT NULL CHECK (ref_type IN ('rental_order','rental_purchase','dj_artist','construction_inquiry','dj_event')),
  ref_id BIGINT NOT NULL,                 -- 원본 엔티티 id
  title TEXT NOT NULL,                    -- 사용자에게 표시되는 제목
  doc_type TEXT NOT NULL DEFAULT 'none' CHECK (doc_type IN ('estimate','contract','none')),
  doc_id BIGINT,                          -- estimates.id 또는 contracts.id
  owner_user_id UUID NOT NULL,            -- 승인 주체(회원). 마이페이지 노출/승인 대상
  customer_name TEXT,
  amount NUMERIC,
  status TEXT NOT NULL DEFAULT 'sent' CHECK (status IN ('sent','approved','rejected','cancelled')),
  user_memo TEXT,                         -- 사용자 승인/거절 사유
  acted_at TIMESTAMPTZ,                   -- 사용자 조치 시각
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW())
);
CREATE INDEX IF NOT EXISTS idx_approval_ref ON public.approval_requests (ref_type, ref_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_approval_owner ON public.approval_requests (owner_user_id, status);

DROP TRIGGER IF EXISTS trg_approval_requests_updated ON public.approval_requests;
CREATE TRIGGER trg_approval_requests_updated BEFORE UPDATE ON public.approval_requests
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.approval_requests ENABLE ROW LEVEL SECURITY;

-- 관리자: 전체 관리 (기존 어드민 테이블과 동일 정책)
DROP POLICY IF EXISTS "approval admin" ON public.approval_requests;
CREATE POLICY "approval admin" ON public.approval_requests FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 사용자: 본인에게 온 승인 요청 조회 + 승인/거절(업데이트)
DROP POLICY IF EXISTS "approval owner read" ON public.approval_requests;
CREATE POLICY "approval owner read" ON public.approval_requests FOR SELECT TO authenticated USING (owner_user_id = auth.uid());
DROP POLICY IF EXISTS "approval owner update" ON public.approval_requests;
CREATE POLICY "approval owner update" ON public.approval_requests FOR UPDATE TO authenticated
  USING (owner_user_id = auth.uid()) WITH CHECK (owner_user_id = auth.uid());

GRANT ALL ON public.approval_requests TO authenticated;
