-- Table structure for dynamic inquiry questions
CREATE TABLE IF NOT EXISTS public.inquiry_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('radio', 'checkbox', 'select', 'text', 'file')),
    options JSONB DEFAULT '[]',
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS policies
ALTER TABLE public.inquiry_questions ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access" ON public.inquiry_questions FOR SELECT USING (true);

-- Allow authenticated admin access (assuming 'authenticated' users are admins)
CREATE POLICY "Allow admin full access" ON public.inquiry_questions FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Grant necessary permissions
GRANT SELECT ON public.inquiry_questions TO anon;
GRANT ALL ON public.inquiry_questions TO authenticated;
