-- 약관 관리: 서비스 이용약관 / 개인정보 처리방침
CREATE TABLE IF NOT EXISTS public.terms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('service','privacy')),
  title TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  version TEXT,
  effective_date DATE,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by TEXT,
  updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_terms_type ON public.terms (type, display_order);

DROP TRIGGER IF EXISTS trg_terms_updated ON public.terms;
CREATE TRIGGER trg_terms_updated BEFORE UPDATE ON public.terms FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.terms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "terms read"  ON public.terms;
DROP POLICY IF EXISTS "terms admin" ON public.terms;
-- 공개 페이지에서 활성 약관 조회 허용
CREATE POLICY "terms read"  ON public.terms FOR SELECT TO anon, authenticated USING (true);
-- 관리자(로그인)만 등록/수정/삭제
CREATE POLICY "terms admin" ON public.terms FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT ON public.terms TO anon;
GRANT ALL    ON public.terms TO authenticated;
