-- 브랜드 관심 저장 (회원별) — 브랜드 페이지 "관심 N + 저장한 회원" 소셜프루프
--  · 누구나 조회 가능(관심 수/저장 회원 표시), 저장/해제는 로그인 회원 본인 것만
--  · user_name 은 표시용 스냅샷(저장 시점) — auth.users 를 공개 조회하지 않기 위해 비정규화 저장
CREATE TABLE IF NOT EXISTS public.rental_brand_favorites (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id   BIGINT NOT NULL REFERENCES public.rental_brands(id) ON DELETE CASCADE,
  user_id    UUID   NOT NULL,                    -- auth.users.id
  user_name  TEXT,                               -- 표시용 이름(저장 시점 스냅샷)
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (brand_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_rbf_brand ON public.rental_brand_favorites (brand_id);
CREATE INDEX IF NOT EXISTS idx_rbf_user  ON public.rental_brand_favorites (user_id);

ALTER TABLE public.rental_brand_favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "rbf read"   ON public.rental_brand_favorites;
DROP POLICY IF EXISTS "rbf insert" ON public.rental_brand_favorites;
DROP POLICY IF EXISTS "rbf delete" ON public.rental_brand_favorites;

CREATE POLICY "rbf read"   ON public.rental_brand_favorites FOR SELECT USING (true);
CREATE POLICY "rbf insert" ON public.rental_brand_favorites FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "rbf delete" ON public.rental_brand_favorites FOR DELETE TO authenticated USING (user_id = auth.uid());

GRANT SELECT                 ON public.rental_brand_favorites TO anon;
GRANT SELECT, INSERT, DELETE ON public.rental_brand_favorites TO authenticated;
