-- =============================================================
-- 시공 문의 내역 (챗봇에서 사용자가 제출한 질의/응답 저장)
--  - answers : [{question, answer}] 순서 보존(JSONB)
--  - 공개 사용자가 INSERT 가능, 조회/수정/삭제는 관리자만
-- =============================================================
CREATE TABLE IF NOT EXISTS public.construction_inquiries (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT,
  phone       TEXT,
  email       TEXT,
  file_name   TEXT,
  answers     JSONB NOT NULL DEFAULT '[]'::jsonb,
  privacy_agree   BOOLEAN NOT NULL DEFAULT false,  -- 개인정보 활용 동의(필수)
  marketing_agree BOOLEAN NOT NULL DEFAULT false,  -- 마케팅 활용 동의(선택)
  status      TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'replied', 'hold')),
  memo        TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by  TEXT
);

DROP TRIGGER IF EXISTS trg_construction_inquiries_updated ON public.construction_inquiries;
CREATE TRIGGER trg_construction_inquiries_updated
  BEFORE UPDATE ON public.construction_inquiries
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.construction_inquiries ENABLE ROW LEVEL SECURITY;

-- 공개 사용자(비회원 포함)도 문의 제출(INSERT) 가능
DROP POLICY IF EXISTS "ci public insert" ON public.construction_inquiries;
CREATE POLICY "ci public insert" ON public.construction_inquiries
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- 조회/수정/삭제는 관리자(authenticated)만
DROP POLICY IF EXISTS "ci admin manage" ON public.construction_inquiries;
CREATE POLICY "ci admin manage" ON public.construction_inquiries
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT INSERT ON public.construction_inquiries TO anon;
GRANT ALL    ON public.construction_inquiries TO authenticated;
