-- 계약서(문서) 관리 — 프리랜서/시공수주/행사수주/렌탈인수/렌탈 계약서
CREATE TABLE IF NOT EXISTS public.contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template TEXT NOT NULL CHECK (template IN ('freelancer','construction_order','event_order','rental_handover','rental')),
  title TEXT NOT NULL,
  customer_name TEXT,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,   -- 템플릿 필드값
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','completed')),
  inquiry_id BIGINT,                          -- (추후) 시공 문의/사용자 연동
  owner_user_id UUID,                         -- (추후) 사용자 마이페이지 노출 대상
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_contracts_template ON public.contracts (template, created_at DESC);

DROP TRIGGER IF EXISTS trg_contracts_updated ON public.contracts;
CREATE TRIGGER trg_contracts_updated BEFORE UPDATE ON public.contracts FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "contracts admin" ON public.contracts;
DROP POLICY IF EXISTS "contracts owner read" ON public.contracts;
CREATE POLICY "contracts admin" ON public.contracts FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- (추후) 사용자 본인 계약서 조회
CREATE POLICY "contracts owner read" ON public.contracts FOR SELECT TO authenticated USING (owner_user_id = auth.uid());
GRANT ALL ON public.contracts TO authenticated;
