-- 렌탈 출고 현황 (계약 후 실제 출고 관리 · 사용자 마이페이지 노출)
CREATE TABLE IF NOT EXISTS public.rental_shipments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT,                         -- 연결된 렌탈 주문(선택)
  contract_id BIGINT,                      -- 연결된 계약서(선택)
  product_name TEXT NOT NULL,
  brand_name TEXT,
  quantity INTEGER NOT NULL DEFAULT 1,
  customer_name TEXT,
  customer_phone TEXT,
  ship_date DATE,                          -- 출고일
  return_date DATE,                        -- 회수 예정일
  tracking_no TEXT,                        -- 송장/추적 번호
  status TEXT NOT NULL DEFAULT 'preparing' CHECK (status IN ('preparing','shipped','delivering','installed','returned')),
  memo TEXT,
  owner_user_id UUID,                      -- 마이페이지 노출 대상(사용자)
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_rental_shipments_ship ON public.rental_shipments (ship_date DESC);
CREATE INDEX IF NOT EXISTS idx_rental_shipments_owner ON public.rental_shipments (owner_user_id);

DROP TRIGGER IF EXISTS trg_rental_shipments_updated ON public.rental_shipments;
CREATE TRIGGER trg_rental_shipments_updated BEFORE UPDATE ON public.rental_shipments
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.rental_shipments ENABLE ROW LEVEL SECURITY;
-- 관리자: 전체 관리
DROP POLICY IF EXISTS "rental_shipments admin" ON public.rental_shipments;
CREATE POLICY "rental_shipments admin" ON public.rental_shipments FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- 사용자: 본인 소유 출고 건만 조회 (마이페이지)
DROP POLICY IF EXISTS "rental_shipments owner read" ON public.rental_shipments;
CREATE POLICY "rental_shipments owner read" ON public.rental_shipments FOR SELECT TO authenticated USING (owner_user_id = auth.uid());
GRANT ALL ON public.rental_shipments TO authenticated;
