-- 사내 공지사항 (관리자 대시보드 상단 노출)
CREATE TABLE IF NOT EXISTS public.admin_notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,   -- 상단 고정
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW())
);
CREATE INDEX IF NOT EXISTS idx_admin_notices_created ON public.admin_notices (pinned DESC, created_at DESC);

DROP TRIGGER IF EXISTS trg_admin_notices_updated ON public.admin_notices;
CREATE TRIGGER trg_admin_notices_updated BEFORE UPDATE ON public.admin_notices
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.admin_notices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "admin_notices admin" ON public.admin_notices;
CREATE POLICY "admin_notices admin" ON public.admin_notices FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT ALL ON public.admin_notices TO authenticated;
