-- =============================================================
-- 시공(Construction) 관리 모듈용 스키마
--  - construction_categories : 시공 분야 카테고리
--  - construction_reviews    : 시공 후기
--  - construction_portfolio  : 시공 포트폴리오
--  - inquiry_questions       : 챗봇 룰베이스(감사/활성 컬럼 보강)
-- 공통: display_order(순번), is_active(활성화), 감사 컬럼
--  (created_at/updated_at/created_by/updated_by) 제공
-- created_by/updated_by 는 관리자 표시명을 그대로 저장(TEXT)하여
--  목록에서 조인 없이 등록자/수정자를 노출한다.
-- =============================================================

-- updated_at 자동 갱신 공용 트리거 함수
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -------------------------------------------------------------
-- 1) 시공 분야 카테고리
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.construction_categories (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  description   TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

DROP TRIGGER IF EXISTS trg_construction_categories_updated ON public.construction_categories;
CREATE TRIGGER trg_construction_categories_updated
  BEFORE UPDATE ON public.construction_categories
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- -------------------------------------------------------------
-- 2) 시공 후기 (사용자 등록 후기 관리)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.construction_reviews (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id   BIGINT REFERENCES public.construction_categories(id) ON DELETE SET NULL,
  author_name   TEXT NOT NULL DEFAULT '익명',
  title         TEXT,
  content       TEXT NOT NULL,
  rating        NUMERIC(2,1) NOT NULL DEFAULT 5.0 CHECK (rating >= 0 AND rating <= 5),
  images        JSONB NOT NULL DEFAULT '[]'::jsonb,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

DROP TRIGGER IF EXISTS trg_construction_reviews_updated ON public.construction_reviews;
CREATE TRIGGER trg_construction_reviews_updated
  BEFORE UPDATE ON public.construction_reviews
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- -------------------------------------------------------------
-- 3) 시공 포트폴리오 (이미지/제목/상세(HTML)/링크 + 카테고리)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.construction_portfolio (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id   BIGINT REFERENCES public.construction_categories(id) ON DELETE SET NULL,
  title         TEXT NOT NULL,
  thumbnail_url TEXT,
  content_html  TEXT,
  link_url      TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by    TEXT,
  updated_by    TEXT
);

DROP TRIGGER IF EXISTS trg_construction_portfolio_updated ON public.construction_portfolio;
CREATE TRIGGER trg_construction_portfolio_updated
  BEFORE UPDATE ON public.construction_portfolio
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- -------------------------------------------------------------
-- RLS & 권한 (공개 읽기 / 인증 관리자 전체)
-- -------------------------------------------------------------
ALTER TABLE public.construction_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.construction_reviews    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.construction_portfolio  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "cc public read"  ON public.construction_categories;
DROP POLICY IF EXISTS "cc admin all"    ON public.construction_categories;
CREATE POLICY "cc public read" ON public.construction_categories FOR SELECT USING (true);
CREATE POLICY "cc admin all"   ON public.construction_categories FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "cr public read"  ON public.construction_reviews;
DROP POLICY IF EXISTS "cr admin all"    ON public.construction_reviews;
CREATE POLICY "cr public read" ON public.construction_reviews FOR SELECT USING (true);
CREATE POLICY "cr admin all"   ON public.construction_reviews FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "cp public read"  ON public.construction_portfolio;
DROP POLICY IF EXISTS "cp admin all"    ON public.construction_portfolio;
CREATE POLICY "cp public read" ON public.construction_portfolio FOR SELECT USING (true);
CREATE POLICY "cp admin all"   ON public.construction_portfolio FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT ON public.construction_categories TO anon;
GRANT SELECT ON public.construction_reviews    TO anon;
GRANT SELECT ON public.construction_portfolio  TO anon;
GRANT ALL    ON public.construction_categories TO authenticated;
GRANT ALL    ON public.construction_reviews    TO authenticated;
GRANT ALL    ON public.construction_portfolio  TO authenticated;

-- -------------------------------------------------------------
-- 4) inquiry_questions(챗봇 룰베이스) 개선:
--    활성화 토글 + 감사 컬럼 + updated_at 트리거
-- -------------------------------------------------------------
ALTER TABLE public.inquiry_questions
  ADD COLUMN IF NOT EXISTS is_active      BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS use_categories BOOLEAN NOT NULL DEFAULT false, -- true면 옵션을 시공 카테고리로 대체(예: "어떤 공간인가요?")
  ADD COLUMN IF NOT EXISTS updated_at     TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()),
  ADD COLUMN IF NOT EXISTS created_by     TEXT,
  ADD COLUMN IF NOT EXISTS updated_by     TEXT;

DROP TRIGGER IF EXISTS trg_inquiry_questions_updated ON public.inquiry_questions;
CREATE TRIGGER trg_inquiry_questions_updated
  BEFORE UPDATE ON public.inquiry_questions
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
