-- 시공 업무 관리(업체/업무 현황) + 견적서(시공/렌탈/DJ)

-- 1) 시공 업체 관리
CREATE TABLE IF NOT EXISTS public.construction_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,            -- 업체명
  manager TEXT,                  -- 담당자
  phone TEXT,
  email TEXT,
  region TEXT,
  memo TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by TEXT, updated_by TEXT
);

-- 2) 시공 업무 현황 (문의 → 담당자/업체 배정 → 일정)
CREATE TABLE IF NOT EXISTS public.construction_works (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_id BIGINT,             -- 연결된 시공 문의(선택)
  title TEXT NOT NULL,
  customer_name TEXT,
  customer_phone TEXT,
  company_id BIGINT REFERENCES public.construction_companies(id) ON DELETE SET NULL,
  company_name TEXT,             -- 배정 시점 업체명 스냅샷
  assignee TEXT,                 -- 담당자
  scheduled_start DATE,
  scheduled_end DATE,
  amount NUMERIC,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','assigned','in_progress','done','hold')),
  memo TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_con_works_sched ON public.construction_works (scheduled_start);

-- 3) 견적서 (시공/렌탈/DJ 프리랜서)
CREATE TABLE IF NOT EXISTS public.estimates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('construction','rental','dj')),
  title TEXT NOT NULL,
  customer_name TEXT,
  customer_phone TEXT,
  customer_email TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,   -- [{name, qty, unit_price, amount}]
  subtotal NUMERIC NOT NULL DEFAULT 0,
  discount NUMERIC NOT NULL DEFAULT 0,
  tax NUMERIC NOT NULL DEFAULT 0,
  total NUMERIC NOT NULL DEFAULT 0,
  valid_until DATE,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','accepted','rejected')),
  memo TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by TEXT, updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_estimates_type ON public.estimates (type, created_at DESC);

-- 트리거 + RLS (관리자 전용)
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['construction_companies','construction_works','estimates'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_updated ON public.%I;', t, t);
    EXECUTE format('CREATE TRIGGER trg_%s_updated BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();', t, t);
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('DROP POLICY IF EXISTS "%s admin" ON public.%I;', t, t);
    EXECUTE format('CREATE POLICY "%s admin" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true);', t, t);
    EXECUTE format('GRANT ALL ON public.%I TO authenticated;', t);
  END LOOP;
END $$;
